In [19]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
import pickle

In [20]:
model=load_model('model.h5')

with open('Label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('OneHotEncoder_geo.pkl','rb') as file:
    OneHotEncoder_geo=pickle.load(file)

with open('StandardScaler','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [21]:
input_data_1 = {
    'CreditScore': 400,
    'Geography': 'Germany',
    'Gender': 'Female',
    'Age': 55,
    'Tenure': 1,
    'Balance': 90000,
    'NumOfProducts': 1,
    'HasCrCard': 0,
    'IsActiveMember': 0,
    'EstimatedSalary': 30000
}

In [22]:
input_df_1=pd.DataFrame([input_data_1])
input_df_1

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          400   Germany  Female  ...          0               0            30000

[1 rows x 10 columns]

In [23]:
geo_encoded=OneHotEncoder_geo.transform([[input_data_1['Geography']]]).toarray()
geo_df=pd.DataFrame(geo_encoded,columns=OneHotEncoder_geo.get_feature_names_out(['Geography']))
geo_df

d:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [24]:
#encode categorical value
input_df_1['Gender']=label_encoder_gender.transform([input_data_1['Gender']])
input_df_1

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          400   Germany       0  ...          0               0            30000

[1 rows x 10 columns]

In [25]:
#concatinate the df
input_df_1=pd.concat([input_df_1.drop('Geography',axis=1),geo_df],axis=1)
input_df_1

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          400       0  ...                1.0              0.0

[1 rows x 12 columns]

In [26]:
#scaling
scaled_input_1=scaler.transform(input_df_1)
scaled_input_1

array([[-2.59160565, -1.09582175,  1.5100953 , -1.39546805,  0.21843582,
        -0.91872163, -1.56232526, -1.02532046, -1.21984564, -1.00551521,
         1.73436329, -0.57388614]])

In [31]:
prediction=model.predict(scaled_input_1)
prediction_prob=prediction[0][0]
print(prediction_prob)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0.94807565

In [28]:
if(prediction_prob>0.5):
    print(f'the customer will exit the bank')
else :
    print(f'person will not exit the bank')

the customer will exit the bank